import type { CharacterId, CharacterProfile, TechniqueDefinition } from "./types.ts";
import { CHARM_EFFECT } from "./combat.ts";

type AssetResolver = (source: string) => string;

const icon = {
  punch:
    '<path d="M11 23v-8a4 4 0 018 0v5-9a4 4 0 018 0v9-7a4 4 0 018 0v9-5a4 4 0 018 0v12c0 10-7 16-16 16-10 0-17-7-17-16v-6a4 4 0 017-3z"/>',
  pentagramNova:
    '<ellipse cx="24" cy="24" rx="21" ry="8" fill="none" stroke="currentColor" stroke-width="3" transform="rotate(-17 24 24)"/><path d="M24 4l4.7 13.5H43l-11.5 8.2L36 40 24 31.4 12 40l4.5-14.3L5 17.5h14.3L24 4z" fill="none" stroke="currentColor" stroke-width="3" stroke-linejoin="round"/><circle cx="24" cy="24" r="3"/>',
  starRing:
    '<ellipse cx="24" cy="25" rx="19" ry="9" fill="none" stroke="currentColor" stroke-width="5" transform="rotate(-15 24 25)"/><path d="M25 5l2.4 8.1 8.1 2.4-8.1 2.4L25 26l-2.4-8.1-8.1-2.4 8.1-2.4L25 5z"/>',
  etoileDrive:
    '<rect x="9" y="4" width="30" height="40" rx="4" fill="none" stroke="currentColor" stroke-width="4"/><path d="M24 9l3.2 9.8L37 22l-9.8 3.2L24 35l-3.2-9.8L11 22l9.8-3.2L24 9z"/><path d="M14 9h4M30 9h4M14 39h4M30 39h4" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/>',
  galaxyRay:
    '<path d="M7 38L32 13l5 5-25 25z"/><path d="M35 3l2.2 7.8L45 13l-7.8 2.2L35 23l-2.2-7.8L25 13l7.8-2.2L35 3z"/>',
  galaxyFlash:
    '<path d="M24 3l4.2 14.8L43 22l-14.8 4.2L24 41l-4.2-14.8L5 22l14.8-4.2L24 3z"/><path d="M8 6l2.1 6.9L17 15l-6.9 2.1L8 24l-2.1-6.9L-1 15l6.9-2.1L8 6zm33 20l1.7 5.3L48 33l-5.3 1.7L41 40l-1.7-5.3L34 33l5.3-1.7L41 26z"/>',
  throwKiss:
    '<path d="M24 13c-5-8-16-5-16 4 0 8 9 14 16 20 7-6 16-12 16-20 0-9-11-12-16-4z"/><path d="M5 39c7-7 13-8 19-4-5 7-12 9-19 4zm0 0c7 3 13 3 19-4" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/>',
  meteorClaw:
    '<path d="M8 11c9 8 18 9 31 8M5 23c11 7 20 7 35 4M8 36c10 4 18 2 30-2" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round"/>',
  crescentHorn: '<path d="M39 5C20 10 10 24 14 43c4-10 11-16 21-19-6-4-5-11 4-19z"/>',
  darkOrbit:
    '<circle cx="24" cy="24" r="9"/><ellipse cx="24" cy="24" rx="21" ry="8" fill="none" stroke="currentColor" stroke-width="4" transform="rotate(-18 24 24)"/><circle cx="41" cy="16" r="3"/>',
  blackMeteor: '<path d="M7 9l18 11-7 7L7 9zm3 18l12 4-5 5-7-9z"/><circle cx="32" cy="31" r="12"/>',
  starTouch:
    '<path d="M24 19l2.4 6.7h7l-5.6 4.1 2.1 6.7-5.9-4-5.9 4 2.1-6.7-5.6-4.1h7L24 19z"/><circle cx="14" cy="15" r="4"/><circle cx="23" cy="11" r="4"/><circle cx="33" cy="15" r="4"/>',
  haloSkip:
    '<ellipse cx="24" cy="15" rx="18" ry="7" fill="none" stroke="currentColor" stroke-width="4" transform="rotate(-12 24 15)"/><path d="M12 34c8-10 17-12 25-8l-8 3 7 6c-9 4-17 3-24-1z"/><path d="M40 7l1.5 4.5L46 13l-4.5 1.5L40 19l-1.5-4.5L34 13l4.5-1.5L40 7z"/>',
  stellaSearch:
    '<rect x="8" y="5" width="27" height="38" rx="4" fill="none" stroke="currentColor" stroke-width="4"/><circle cx="21.5" cy="24" r="8" fill="none" stroke="currentColor" stroke-width="3"/><path d="M21.5 11v6m0 14v6M9 24h6m13 0h12M36 17l5-5m-5 19l5 5" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/>',
  discoveryComet:
    '<path d="M32 5l3.4 10.6L46 19l-10.6 3.4L32 33l-3.4-10.6L18 19l10.6-3.4L32 5z"/><path d="M5 38c7-10 13-14 20-16M8 43c6-8 10-11 16-14" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round"/>',
  nap: '<path d="M27 7c-9 3-14 12-11 21 3 8 12 12 21 8-6 0-12-4-14-10-2-7 0-14 4-19z"/><path d="M7 34h27v9H7z"/><path d="M35 8h8l-8 7h8l-8 7" fill="none" stroke="currentColor" stroke-width="3" stroke-linejoin="round"/>',
  businessCard:
    '<rect x="7" y="11" width="28" height="19" rx="2" fill="none" stroke="currentColor" stroke-width="3" transform="rotate(-12 21 20)"/><rect x="14" y="18" width="28" height="19" rx="2" fill="none" stroke="currentColor" stroke-width="3" transform="rotate(9 28 27)"/><path d="M21 24h13M23 29h8" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/>',
  closingTime:
    '<circle cx="17" cy="17" r="10" fill="none" stroke="currentColor" stroke-width="4"/><path d="M17 11v7l5 3M24 30h17v13H14V30h4v-4h8v4" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><path d="M14 35h27" fill="none" stroke="currentColor" stroke-width="3"/>',
  angelWink:
    '<path d="M5 19c5-7 13-8 19-1-6 7-14 7-19 1z" fill="none" stroke="currentColor" stroke-width="3"/><circle cx="15" cy="19" r="3"/><path d="M31 14c-5-7-14-3-14 4 0 7 8 12 14 18 6-6 14-11 14-18 0-7-9-11-14-4z"/><path d="M6 35c5 4 10 4 15 0" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/>',
  approvalMeteor:
    '<path d="M7 7h24v31H7zM13 14h12M13 20h12M13 26h8" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><circle cx="33" cy="33" r="10"/><path d="M29 33l3 3 6-7" fill="none" stroke="white" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><path d="M38 5l2 6 6 2-6 2-2 6-2-6-6-2 6-2z"/>',
  tatsuoSlap:
    '<path d="M8 25c8-2 13-7 17-15l7 4-5 9 13-5 3 7-14 8c-8 5-16 3-21-8z"/><path d="M5 39c9-4 17-3 25 3" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round"/>',
  tatsuoRestraint:
    '<path d="M6 9h11v13H6zM31 9h11v13H31z"/><path d="M12 22v10c0 7 5 11 12 11s12-4 12-11V22" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round"/><path d="M16 31h16" fill="none" stroke="currentColor" stroke-width="4"/>',
  tatsuoRoar:
    '<path d="M5 17c10 0 16-4 21-11v36c-5-7-11-11-21-11z"/><path d="M31 14c7 3 10 7 12 11M32 25c6 1 9 3 12 7M32 7c7 4 11 9 14 16" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round"/>',
  tatsuoPress:
    '<path d="M7 31l14-18 20 15-14 15z"/><path d="M12 9l8 6M35 8l-6 10M42 34l-8-3" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round"/>',
} as const;

const etokichiTechniques: TechniqueDefinition[] = [
  {
    id: "punch",
    name: "エトキチパンチ",
    iconSvg: icon.punch,
    cost: 16,
    power: 90,
    accuracy: 91,
    critical: 8,
    range: 0,
    duration: 2200,
    cameraReleaseDelay: 820,
    impactDelay: 1250,
    kind: "strike",
    animation: "physicalPunch",
    attackStat: "power",
    gutsDamage: 0,
  },
  {
    id: "pentagramNova",
    name: "エトキチ・ペンタグラムノヴァ",
    cardName: "ペンタグラムノヴァ",
    iconSvg: icon.pentagramNova,
    cost: 62,
    power: 380,
    accuracy: 55,
    critical: 32,
    range: 0,
    duration: 6500,
    cameraReleaseDelay: 1120,
    impactDelay: 5200,
    kind: "super",
    animation: "pentagramNova",
    attackStat: "power",
    gutsDamage: 26,
    knockback: 70,
  },
  {
    id: "starRing",
    name: "スターリング",
    iconSvg: icon.starRing,
    cost: 24,
    power: 124,
    accuracy: 81,
    critical: 16,
    range: 1,
    duration: 2700,
    cameraReleaseDelay: 880,
    impactDelay: 1650,
    kind: "strike",
    animation: "physicalStarRing",
    attackStat: "power",
    gutsDamage: 12,
  },
  {
    id: "etoileDrive",
    name: "エトワール・ドライブ",
    iconSvg: icon.etoileDrive,
    cost: 32,
    power: 0,
    accuracy: 100,
    critical: 0,
    range: 1,
    duration: 3400,
    kind: "support",
    animation: "etoileDrive",
    attackStat: "intelligence",
    gutsDamage: 0,
  },
  {
    id: "galaxyRay",
    name: "ギャラクシーレイ",
    iconSvg: icon.galaxyRay,
    cost: 32,
    power: 172,
    accuracy: 71,
    critical: 12,
    range: 2,
    duration: 2800,
    cameraReleaseDelay: 1210,
    impactDelay: 1900,
    kind: "shot",
    animation: "galaxyRay",
    attackStat: "intelligence",
    gutsDamage: 5,
  },
  {
    id: "galaxyFlash",
    name: "エトキチギャラクシーフラッシュ",
    cardName: "ギャラクシーフラッシュ",
    iconSvg: icon.galaxyFlash,
    cost: 48,
    power: 292,
    accuracy: 62,
    critical: 24,
    range: 3,
    duration: 4600,
    cameraReleaseDelay: 2700,
    kind: "special",
    animation: "galaxyFlash",
    attackStat: "intelligence",
    gutsDamage: 18,
    knockback: 35,
  },
  {
    id: "throwKiss",
    name: "投げキッス",
    iconSvg: icon.throwKiss,
    cost: 20,
    power: 46,
    accuracy: 93,
    critical: 5,
    range: 2,
    duration: 2800,
    cameraReleaseDelay: 950,
    impactDelay: 1850,
    kind: "shot",
    animation: "throwKiss",
    attackStat: "intelligence",
    gutsDamage: 32,
  },
];

const kuroboshiTechniques: TechniqueDefinition[] = [
  {
    id: "meteorClaw",
    name: "メテオクロー",
    iconSvg: icon.meteorClaw,
    cost: 16,
    power: 82,
    accuracy: 88,
    critical: 10,
    range: 0,
    duration: 2300,
    cameraReleaseDelay: 850,
    impactDelay: 1350,
    kind: "strike",
    animation: "physicalMeteorClaw",
    attackStat: "power",
    gutsDamage: 0,
  },
  {
    id: "crescentHorn",
    name: "クレセントホーン",
    iconSvg: icon.crescentHorn,
    cost: 23,
    power: 118,
    accuracy: 78,
    critical: 18,
    range: 1,
    duration: 2900,
    cameraReleaseDelay: 940,
    impactDelay: 1800,
    kind: "strike",
    animation: "physicalCrescentHorn",
    attackStat: "power",
    gutsDamage: 8,
  },
  {
    id: "darkOrbit",
    name: "ダークオービット",
    iconSvg: icon.darkOrbit,
    cost: 30,
    power: 154,
    accuracy: 69,
    critical: 14,
    range: 2,
    duration: 3200,
    cameraReleaseDelay: 1100,
    impactDelay: 2200,
    kind: "shot",
    animation: "darkOrbit",
    attackStat: "intelligence",
    gutsDamage: 14,
  },
  {
    id: "blackMeteor",
    name: "ブラックメテオ",
    iconSvg: icon.blackMeteor,
    cost: 43,
    power: 230,
    accuracy: 59,
    critical: 25,
    range: 3,
    duration: 4200,
    cameraReleaseDelay: 1200,
    impactDelay: 3000,
    kind: "shot",
    animation: "blackMeteor",
    attackStat: "intelligence",
    gutsDamage: 0,
  },
];

const sutekichiTechniques: TechniqueDefinition[] = [
  {
    id: "starTouch",
    name: "スターダストタッチ",
    iconSvg: icon.starTouch,
    cost: 15,
    power: 68,
    accuracy: 94,
    critical: 8,
    range: 0,
    duration: 2300,
    cameraReleaseDelay: 850,
    impactDelay: 1350,
    kind: "strike",
    animation: "sutekichiStarTouch",
    attackStat: "power",
    gutsDamage: 8,
  },
  {
    id: "haloSkip",
    name: "ハロースキップ",
    iconSvg: icon.haloSkip,
    cost: 22,
    power: 108,
    accuracy: 84,
    critical: 14,
    range: 1,
    duration: 2900,
    cameraReleaseDelay: 940,
    impactDelay: 1800,
    kind: "strike",
    animation: "sutekichiHaloSkip",
    attackStat: "power",
    gutsDamage: 12,
  },
  {
    id: "stellaSearch",
    name: "ステラサーチ",
    iconSvg: icon.stellaSearch,
    cost: 29,
    power: 142,
    accuracy: 78,
    critical: 10,
    range: 2,
    duration: 3200,
    cameraReleaseDelay: 1100,
    impactDelay: 2200,
    kind: "shot",
    animation: "sutekichiStellaSearch",
    attackStat: "intelligence",
    gutsDamage: 20,
  },
  {
    id: "discoveryComet",
    name: "ディスカバリー・コメット",
    iconSvg: icon.discoveryComet,
    cost: 46,
    power: 248,
    accuracy: 60,
    critical: 22,
    range: 3,
    duration: 4200,
    cameraReleaseDelay: 1200,
    impactDelay: 3000,
    kind: "shot",
    animation: "sutekichiDiscoveryComet",
    attackStat: "intelligence",
    gutsDamage: 10,
  },
  {
    id: "nap",
    name: "おひるね",
    iconSvg: icon.nap,
    cost: 55,
    power: 0,
    accuracy: 65,
    critical: 0,
    range: 3,
    duration: 4500,
    cameraReleaseDelay: 1100,
    impactDelay: 3000,
    kind: "support",
    animation: "sutekichiNap",
    attackStat: "intelligence",
    gutsDamage: 0,
    healFull: true,
    successChance: 65,
  },
];

const salarymanEtokichiTechniques: TechniqueDefinition[] = [
  {
    id: "businessCardStrike",
    name: "名刺ストライク",
    iconSvg: icon.businessCard,
    cost: 15,
    power: 76,
    accuracy: 94,
    critical: 9,
    range: 0,
    duration: 2300,
    cameraReleaseDelay: 850,
    impactDelay: 1370,
    kind: "strike",
    animation: "businessCardStrike",
    attackStat: "power",
    gutsDamage: 8,
  },
  {
    id: "angelWink",
    name: "エンジェルウィンク",
    iconSvg: icon.angelWink,
    cost: 31,
    power: 54,
    accuracy: 89,
    critical: 6,
    range: 2,
    duration: 3200,
    cameraReleaseDelay: 1080,
    impactDelay: 2150,
    kind: "shot",
    animation: "angelWink",
    attackStat: "intelligence",
    gutsDamage: 28,
    charmChance: CHARM_EFFECT.triggerChance,
  },
  {
    id: "approvalMeteor",
    name: "稟議書メテオ",
    iconSvg: icon.approvalMeteor,
    cost: 45,
    power: 238,
    accuracy: 61,
    critical: 22,
    range: 3,
    duration: 4200,
    cameraReleaseDelay: 1220,
    impactDelay: 3050,
    kind: "shot",
    animation: "approvalMeteor",
    attackStat: "intelligence",
    gutsDamage: 18,
  },
  {
    id: "closingTimeDash",
    name: "定時ダッシュ",
    iconSvg: icon.closingTime,
    cost: 24,
    power: 126,
    accuracy: 82,
    critical: 15,
    range: 3,
    duration: 550,
    cameraReleaseDelay: 100,
    impactDelay: 400,
    kind: "strike",
    animation: "closingTimeDash",
    attackStat: "power",
    gutsDamage: 14,
    closesDistance: true,
  },
];

const tatsuoTechniques: TechniqueDefinition[] = [
  {
    id: "tatsuoSlap",
    name: "タツヲビンタ",
    iconSvg: icon.tatsuoSlap,
    cost: 14,
    power: 82,
    accuracy: 90,
    critical: 8,
    range: 0,
    duration: 2300,
    cameraReleaseDelay: 850,
    impactDelay: 1370,
    kind: "strike",
    animation: "tatsuoSlap",
    attackStat: "power",
    gutsDamage: 14,
  },
  {
    id: "tatsuoRestraint",
    name: "取り押さえ",
    iconSvg: icon.tatsuoRestraint,
    cost: 42,
    power: 105,
    accuracy: 61,
    critical: 5,
    range: 1,
    duration: 3200,
    cameraReleaseDelay: 1040,
    impactDelay: 2150,
    kind: "strike",
    animation: "tatsuoRestraint",
    attackStat: "power",
    gutsDamage: 18,
    restraintDuration: 8000,
  },
  {
    id: "tatsuoRoar",
    name: "腹の底から咆哮",
    iconSvg: icon.tatsuoRoar,
    cost: 30,
    power: 35,
    accuracy: 86,
    critical: 4,
    range: 2,
    duration: 3200,
    cameraReleaseDelay: 1080,
    impactDelay: 2200,
    kind: "shot",
    animation: "tatsuoRoar",
    attackStat: "intelligence",
    gutsDamage: 46,
    knockback: 42,
  },
  {
    id: "tatsuoPress",
    name: "タツヲプレス",
    iconSvg: icon.tatsuoPress,
    cost: 50,
    power: 275,
    accuracy: 57,
    critical: 18,
    range: 3,
    duration: 4200,
    cameraReleaseDelay: 1200,
    impactDelay: 3020,
    kind: "special",
    animation: "tatsuoPress",
    attackStat: "power",
    gutsDamage: 18,
    knockback: 28,
    closesDistance: true,
  },
];

export function createCharacterProfiles(resolveAsset: AssetResolver): Record<CharacterId, CharacterProfile> {
  const asset = resolveAsset;
  return {
    etokichi: {
      id: "etokichi",
      baseFacing: "right",
      name: "エトキチ",
      subtitle: "GALAXY TRAIL",
      abilitiesLabel: "底力・根性・余裕・明鏡止水・覚醒",
      images: {
        idle: asset("assets/etokichi/idle.webp"),
        battleIdle: asset("assets/etokichi/walk-right-2.webp"),
        galaxyCharge: asset("assets/etokichi/galaxy-charge.webp"),
        cast: asset("assets/etokichi/cast.webp"),
        galaxyRecoil: asset("assets/etokichi/galaxy-recoil.webp"),
        galaxyRayCast: asset("assets/etokichi/galaxy-ray-cast.webp"),
        punchCast: asset("assets/etokichi/punch-cast.webp"),
        starRingCast: asset("assets/etokichi/star-ring-cast.webp"),
        pentagramNovaWindup: asset("assets/etokichi/pentagram-nova-windup.webp"),
        pentagramNovaRush: asset("assets/etokichi/pentagram-nova-rush.webp"),
        pentagramNovaDive: asset("assets/etokichi/pentagram-nova-dive.webp"),
        etoileDriveCast: asset("assets/etokichi/etoile-drive-cast.webp"),
        throwKissCast: asset("assets/etokichi/throw-kiss-cast.webp"),
        statusSerenity: asset("assets/etokichi/status-serenity.webp"),
        victoryClimax: asset("assets/etokichi/victory-climax.webp"),
        defeat: asset("assets/etokichi/defeat.webp"),
        walk: [1, 2, 3].map((frame) => asset(`assets/etokichi/walk-right-${frame}.webp`)),
      },
      introPoseKeys: ["battleIdle", "punchCast", "battleIdle", "starRingCast"],
      versusPoseKey: "battleIdle",
      stats: { life: 500, power: 410, defense: 420, accuracy: 480, evasion: 430, intelligence: 560, gutsRegen: 2.7 },
      abilities: ["power", "grit", "ease", "serenity", "awakening"],
      techniques: etokichiTechniques,
    },
    kuroboshi: {
      id: "kuroboshi",
      baseFacing: "left",
      name: "クロボシ",
      subtitle: "VOID METEOR",
      abilitiesLabel: "本気・余裕・嫉妬",
      images: {
        idle: asset("assets/enemies/kuroboshi/idle.webp"),
        battleIdle: asset("assets/enemies/kuroboshi/idle.webp"),
        darkOrbitCast: asset("assets/enemies/kuroboshi/dark-orbit-cast.webp"),
        blackMeteorCast: asset("assets/enemies/kuroboshi/black-meteor-cast.webp"),
        meteorClawCast: asset("assets/enemies/kuroboshi/meteor-claw-cast.webp"),
        crescentHornCast: asset("assets/enemies/kuroboshi/crescent-horn-cast.webp"),
        statusEase: asset("assets/enemies/kuroboshi/status-ease.webp"),
        statusInspiration: asset("assets/enemies/kuroboshi/status-ease.webp"),
        victoryClimax: asset("assets/enemies/kuroboshi/victory-climax.webp"),
        walk: [1, 2, 3].map((frame) => asset(`assets/enemies/kuroboshi/walk-${frame}.webp`)),
      },
      introPoseKeys: ["idle", "meteorClawCast", "idle", "crescentHornCast"],
      versusPoseKey: "crescentHornCast",
      stats: { life: 625, power: 520, defense: 500, accuracy: 420, evasion: 350, intelligence: 420, gutsRegen: 2.5 },
      abilities: ["real", "ease", "jealousy"],
      techniques: kuroboshiTechniques,
    },
    sutekichi: {
      id: "sutekichi",
      baseFacing: "left",
      name: "ステキチ",
      subtitle: "STELLAR GUIDE",
      abilitiesLabel: "ひらめき・余裕",
      images: {
        idle: asset("assets/enemies/sutekichi/idle.webp"),
        battleIdle: asset("assets/enemies/sutekichi/idle.webp"),
        stellaSearchCast: asset("assets/enemies/sutekichi/stella-search-cast.webp"),
        discoveryCometCast: asset("assets/enemies/sutekichi/discovery-comet-cast.webp"),
        starTouchCast: asset("assets/enemies/sutekichi/star-touch-cast.webp"),
        haloSkipCast: asset("assets/enemies/sutekichi/halo-skip-cast.webp"),
        napCast: asset("assets/enemies/sutekichi/nap-cast.webp"),
        statusEase: asset("assets/enemies/sutekichi/status-inspiration.webp"),
        statusInspiration: asset("assets/enemies/sutekichi/status-inspiration.webp"),
        statusGenki: asset("assets/enemies/sutekichi/status-genki.webp"),
        victoryClimax: asset("assets/enemies/sutekichi/victory-climax.webp"),
        walk: [1, 2, 3].map((frame) => asset(`assets/enemies/sutekichi/walk-${frame}.webp`)),
      },
      introPoseKeys: ["idle", "starTouchCast", "idle", "haloSkipCast"],
      versusPoseKey: "haloSkipCast",
      stats: { life: 430, power: 330, defense: 300, accuracy: 620, evasion: 780, intelligence: 620, gutsRegen: 5.4 },
      abilities: ["inspiration", "ease"],
      techniques: sutekichiTechniques,
    },
    salarymanEtokichi: {
      id: "salarymanEtokichi",
      baseFacing: "left",
      imageFacings: {
        businessCardStrikeCast: "right",
        closingTimeDashCast: "right",
      },
      visualScale: 1.2,
      name: "サラリーマンエトキチ",
      subtitle: "STELLAR BUSINESS",
      abilitiesLabel: "ひらめき・余裕・ゾーン",
      images: {
        idle: asset("assets/characters/salaryman-etokichi/idle.webp"),
        battleIdle: asset("assets/characters/salaryman-etokichi/idle.webp"),
        businessCardStrikeCast: asset("assets/characters/salaryman-etokichi/business-card-strike-cast.webp"),
        closingTimeDashCast: asset("assets/characters/salaryman-etokichi/closing-time-dash-cast.webp"),
        angelWinkCast: asset("assets/characters/salaryman-etokichi/angel-wink-cast.webp"),
        approvalMeteorCast: asset("assets/characters/salaryman-etokichi/approval-meteor-cast.webp"),
        victoryClimax: asset("assets/characters/salaryman-etokichi/victory-climax.webp"),
        defeat: asset("assets/characters/salaryman-etokichi/defeat.webp"),
        walk: [1, 2, 3].map((frame) => asset(`assets/characters/salaryman-etokichi/walk-${frame}.webp`)),
      },
      introPoseKeys: ["idle", "businessCardStrikeCast", "idle", "angelWinkCast"],
      versusPoseKey: "businessCardStrikeCast",
      stats: { life: 540, power: 430, defense: 470, accuracy: 590, evasion: 440, intelligence: 650, gutsRegen: 3.1 },
      abilities: ["inspiration", "ease", "zone"],
      techniques: salarymanEtokichiTechniques,
    },
    tatsuo: {
      id: "tatsuo",
      baseFacing: "left",
      visualScale: 1.08,
      name: "タツヲ",
      subtitle: "SOFT PURSUER",
      abilitiesLabel: "本気・追跡・快感",
      images: {
        idle: asset("assets/characters/tatsuo/idle.webp"),
        battleIdle: asset("assets/characters/tatsuo/idle.webp"),
        slapCast: asset("assets/characters/tatsuo/slap-cast.webp"),
        restraintCast: asset("assets/characters/tatsuo/restraint-cast.webp"),
        roarCast: asset("assets/characters/tatsuo/roar-cast.webp"),
        pressCast: asset("assets/characters/tatsuo/press-cast.webp"),
        statusPleasure: asset("assets/characters/tatsuo/status-pleasure.webp"),
        victoryClimax: asset("assets/characters/tatsuo/victory-climax.webp"),
        defeat: asset("assets/characters/tatsuo/defeat.webp"),
        walk: [
          asset("assets/characters/tatsuo/walk-1.webp"),
          asset("assets/characters/tatsuo/idle.webp"),
          asset("assets/characters/tatsuo/walk-3.webp"),
        ],
      },
      introPoseKeys: ["idle", "slapCast", "idle", "roarCast"],
      versusPoseKey: "restraintCast",
      stats: { life: 680, power: 600, defense: 540, accuracy: 390, evasion: 250, intelligence: 260, gutsRegen: 2.3 },
      abilities: ["real", "pursuit", "pleasure"],
      techniques: tatsuoTechniques,
    },
  };
}
