import type { CharacterId, CharacterProfile, TechniqueDefinition } from "./types.ts";
import { CHARM_EFFECT, PETRIFICATION_EFFECT } from "./combat.ts";

type AssetResolver = (source: string) => string;

const icon = {
  punch:
    '<path d="M11 23v-8a4 4 0 018 0v5-9a4 4 0 018 0v9-7a4 4 0 018 0v9-5a4 4 0 018 0v12c0 10-7 16-16 16-10 0-17-7-17-16v-6a4 4 0 017-3z"/>',
  pentagramNova:
    '<ellipse cx="24" cy="24" rx="21" ry="8" fill="none" stroke="currentColor" stroke-width="3" transform="rotate(-17 24 24)"/><path d="M24 4l4.7 13.5H43l-11.5 8.2L36 40 24 31.4 12 40l4.5-14.3L5 17.5h14.3L24 4z" fill="none" stroke="currentColor" stroke-width="3" stroke-linejoin="round"/><circle cx="24" cy="24" r="3"/>',
  starRing:
    '<ellipse cx="24" cy="25" rx="19" ry="9" fill="none" stroke="currentColor" stroke-width="5" transform="rotate(-15 24 25)"/><path d="M25 5l2.4 8.1 8.1 2.4-8.1 2.4L25 26l-2.4-8.1-8.1-2.4 8.1-2.4L25 5z"/>',
  etoileDrive:
    '<rect x="9" y="4" width="30" height="40" rx="4" fill="none" stroke="currentColor" stroke-width="4"/><path d="M24 9l3.2 9.8L37 22l-9.8 3.2L24 35l-3.2-9.8L11 22l9.8-3.2L24 9z"/><path d="M14 9h4M30 9h4M14 39h4M30 39h4" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/>',
  galaxyRay:
    '<path d="M7 38L32 13l5 5-25 25z"/><path d="M35 3l2.2 7.8L45 13l-7.8 2.2L35 23l-2.2-7.8L25 13l7.8-2.2L35 3z"/>',
  galaxyFlash:
    '<path d="M24 3l4.2 14.8L43 22l-14.8 4.2L24 41l-4.2-14.8L5 22l14.8-4.2L24 3z"/><path d="M8 6l2.1 6.9L17 15l-6.9 2.1L8 24l-2.1-6.9L-1 15l6.9-2.1L8 6zm33 20l1.7 5.3L48 33l-5.3 1.7L41 40l-1.7-5.3L34 33l5.3-1.7L41 26z"/>',
  throwKiss:
    '<path d="M24 13c-5-8-16-5-16 4 0 8 9 14 16 20 7-6 16-12 16-20 0-9-11-12-16-4z"/><path d="M5 39c7-7 13-8 19-4-5 7-12 9-19 4zm0 0c7 3 13 3 19-4" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/>',
  meteorClaw:
    '<path d="M8 11c9 8 18 9 31 8M5 23c11 7 20 7 35 4M8 36c10 4 18 2 30-2" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round"/>',
  crescentHorn: '<path d="M39 5C20 10 10 24 14 43c4-10 11-16 21-19-6-4-5-11 4-19z"/>',
  darkOrbit:
    '<circle cx="24" cy="24" r="9"/><ellipse cx="24" cy="24" rx="21" ry="8" fill="none" stroke="currentColor" stroke-width="4" transform="rotate(-18 24 24)"/><circle cx="41" cy="16" r="3"/>',
  blackMeteor: '<path d="M7 9l18 11-7 7L7 9zm3 18l12 4-5 5-7-9z"/><circle cx="32" cy="31" r="12"/>',
  starTouch:
    '<path d="M24 19l2.4 6.7h7l-5.6 4.1 2.1 6.7-5.9-4-5.9 4 2.1-6.7-5.6-4.1h7L24 19z"/><circle cx="14" cy="15" r="4"/><circle cx="23" cy="11" r="4"/><circle cx="33" cy="15" r="4"/>',
  haloSkip:
    '<ellipse cx="24" cy="15" rx="18" ry="7" fill="none" stroke="currentColor" stroke-width="4" transform="rotate(-12 24 15)"/><path d="M12 34c8-10 17-12 25-8l-8 3 7 6c-9 4-17 3-24-1z"/><path d="M40 7l1.5 4.5L46 13l-4.5 1.5L40 19l-1.5-4.5L34 13l4.5-1.5L40 7z"/>',
  stellaSearch:
    '<rect x="8" y="5" width="27" height="38" rx="4" fill="none" stroke="currentColor" stroke-width="4"/><circle cx="21.5" cy="24" r="8" fill="none" stroke="currentColor" stroke-width="3"/><path d="M21.5 11v6m0 14v6M9 24h6m13 0h12M36 17l5-5m-5 19l5 5" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/>',
  discoveryComet:
    '<path d="M32 5l3.4 10.6L46 19l-10.6 3.4L32 33l-3.4-10.6L18 19l10.6-3.4L32 5z"/><path d="M5 38c7-10 13-14 20-16M8 43c6-8 10-11 16-14" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round"/>',
  nap: '<path d="M27 7c-9 3-14 12-11 21 3 8 12 12 21 8-6 0-12-4-14-10-2-7 0-14 4-19z"/><path d="M7 34h27v9H7z"/><path d="M35 8h8l-8 7h8l-8 7" fill="none" stroke="currentColor" stroke-width="3" stroke-linejoin="round"/>',
  businessCard:
    '<rect x="7" y="11" width="28" height="19" rx="2" fill="none" stroke="currentColor" stroke-width="3" transform="rotate(-12 21 20)"/><rect x="14" y="18" width="28" height="19" rx="2" fill="none" stroke="currentColor" stroke-width="3" transform="rotate(9 28 27)"/><path d="M21 24h13M23 29h8" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/>',
  closingTime:
    '<circle cx="17" cy="17" r="10" fill="none" stroke="currentColor" stroke-width="4"/><path d="M17 11v7l5 3M24 30h17v13H14V30h4v-4h8v4" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><path d="M14 35h27" fill="none" stroke="currentColor" stroke-width="3"/>',
  angelWink:
    '<path d="M5 19c5-7 13-8 19-1-6 7-14 7-19 1z" fill="none" stroke="currentColor" stroke-width="3"/><circle cx="15" cy="19" r="3"/><path d="M31 14c-5-7-14-3-14 4 0 7 8 12 14 18 6-6 14-11 14-18 0-7-9-11-14-4z"/><path d="M6 35c5 4 10 4 15 0" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/>',
  approvalMeteor:
    '<path d="M7 7h24v31H7zM13 14h12M13 20h12M13 26h8" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><circle cx="33" cy="33" r="10"/><path d="M29 33l3 3 6-7" fill="none" stroke="white" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><path d="M38 5l2 6 6 2-6 2-2 6-2-6-6-2 6-2z"/>',
  tatsuoSlap:
    '<path d="M8 25c8-2 13-7 17-15l7 4-5 9 13-5 3 7-14 8c-8 5-16 3-21-8z"/><path d="M5 39c9-4 17-3 25 3" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round"/>',
  tatsuoRestraint:
    '<path d="M6 9h11v13H6zM31 9h11v13H31z"/><path d="M12 22v10c0 7 5 11 12 11s12-4 12-11V22" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round"/><path d="M16 31h16" fill="none" stroke="currentColor" stroke-width="4"/>',
  tatsuoRoar:
    '<path d="M5 17c10 0 16-4 21-11v36c-5-7-11-11-21-11z"/><path d="M31 14c7 3 10 7 12 11M32 25c6 1 9 3 12 7M32 7c7 4 11 9 14 16" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round"/>',
  tatsuoPress:
    '<path d="M7 31l14-18 20 15-14 15z"/><path d="M12 9l8 6M35 8l-6 10M42 34l-8-3" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round"/>',
  deathEnergy:
    '<path d="M10 38c10-16 16-24 27-31" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round"/><circle cx="36" cy="10" r="7"/><path d="M8 9l3 7 7 3-7 3-3 7-3-7-7-3 7-3zM35 27l2 5 5 2-5 2-2 5-2-5-5-2 5-2z"/>',
  evilEye:
    '<path d="M4 24c10-14 30-14 40 0-10 14-30 14-40 0z" fill="none" stroke="currentColor" stroke-width="4"/><circle cx="24" cy="24" r="8"/><path d="M24 16v16M16 24h16" fill="none" stroke="currentColor" stroke-width="2"/>',
  migration:
    '<path d="M6 24h27M25 15l9 9-9 9" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/><path d="M42 8v32M36 14l6-6 6 6M36 34l6 6 6-6" fill="none" stroke="currentColor" stroke-width="3"/>',
  tailSweep:
    '<path d="M7 12c21-5 34 4 34 15 0 9-9 15-22 12-7-2-10-7-8-12 2-4 8-5 13-2" fill="none" stroke="currentColor" stroke-width="6" stroke-linecap="round"/><path d="M35 8l7 4-6 5" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>',
} as const;

const etokichiTechniques: TechniqueDefinition[] = [
  {
    id: "punch",
    name: "エトキチパンチ",
    description: "低コストで素早く放つ、近距離の基本打撃。",
    iconSvg: icon.punch,
    cost: 16,
    power: 90,
    accuracy: 91,
    critical: 8,
    range: 0,
    duration: 2200,
    cameraReleaseDelay: 820,
    impactDelay: 1250,
    kind: "strike",
    animation: "physicalPunch",
    attackStat: "power",
    gutsDamage: 0,
  },
  {
    id: "pentagramNova",
    name: "エトキチ・ペンタグラムノヴァ",
    cardName: "ペンタグラムノヴァ",
    description: "星型の軌道で突撃する、高威力・高消費の大技。",
    iconSvg: icon.pentagramNova,
    cost: 62,
    power: 380,
    accuracy: 55,
    critical: 32,
    range: 0,
    duration: 6500,
    cameraReleaseDelay: 1120,
    impactDelay: 5200,
    kind: "super",
    animation: "pentagramNova",
    attackStat: "power",
    gutsDamage: 26,
    knockback: 70,
  },
  {
    id: "starRing",
    name: "スターリング",
    description: "星の輪をまとって打撃。命中と威力のバランス型。",
    iconSvg: icon.starRing,
    cost: 24,
    power: 124,
    accuracy: 81,
    critical: 16,
    range: 1,
    duration: 2700,
    cameraReleaseDelay: 880,
    impactDelay: 1650,
    kind: "strike",
    animation: "physicalStarRing",
    attackStat: "power",
    gutsDamage: 12,
  },
  {
    id: "etoileDrive",
    name: "エトワール・ドライブ",
    description: "攻撃せず距離を詰め、近距離の大技へつなげる。",
    iconSvg: icon.etoileDrive,
    cost: 32,
    power: 0,
    accuracy: 100,
    critical: 0,
    range: 1,
    duration: 3400,
    kind: "support",
    animation: "etoileDrive",
    attackStat: "intelligence",
    gutsDamage: 0,
  },
  {
    id: "galaxyRay",
    name: "ギャラクシーレイ",
    description: "直線状の光線で攻撃。遠距離の軸になるかしこさ技。",
    iconSvg: icon.galaxyRay,
    cost: 32,
    power: 172,
    accuracy: 71,
    critical: 12,
    range: 2,
    duration: 2800,
    cameraReleaseDelay: 1210,
    impactDelay: 1900,
    kind: "shot",
    animation: "galaxyRay",
    attackStat: "intelligence",
    gutsDamage: 5,
  },
  {
    id: "galaxyFlash",
    name: "エトキチギャラクシーフラッシュ",
    cardName: "ギャラクシーフラッシュ",
    description: "遠間から星光を収束。高威力と吹き飛ばしを両立する。",
    iconSvg: icon.galaxyFlash,
    cost: 48,
    power: 292,
    accuracy: 62,
    critical: 24,
    range: 3,
    duration: 4600,
    cameraReleaseDelay: 2700,
    kind: "special",
    animation: "galaxyFlash",
    attackStat: "intelligence",
    gutsDamage: 18,
    knockback: 35,
  },
  {
    id: "throwKiss",
    name: "投げキッス",
    description: "高い命中でガッツを大きく削る、遠距離の牽制技。",
    iconSvg: icon.throwKiss,
    cost: 20,
    power: 46,
    accuracy: 93,
    critical: 5,
    range: 2,
    duration: 2800,
    cameraReleaseDelay: 950,
    impactDelay: 1850,
    kind: "shot",
    animation: "throwKiss",
    attackStat: "intelligence",
    gutsDamage: 32,
  },
];

const kuroboshiTechniques: TechniqueDefinition[] = [
  {
    id: "meteorClaw",
    name: "メテオクロー",
    description: "鋭い爪で切り裂く、命中に優れた近距離の基本技。",
    iconSvg: icon.meteorClaw,
    cost: 16,
    power: 82,
    accuracy: 89,
    critical: 10,
    range: 0,
    duration: 2300,
    cameraReleaseDelay: 850,
    impactDelay: 1350,
    kind: "strike",
    animation: "physicalMeteorClaw",
    attackStat: "power",
    gutsDamage: 0,
  },
  {
    id: "crescentHorn",
    name: "クレセントホーン",
    description: "三日月の角で突き上げる、威力と命中のバランス技。",
    iconSvg: icon.crescentHorn,
    cost: 23,
    power: 118,
    accuracy: 79,
    critical: 18,
    range: 1,
    duration: 2900,
    cameraReleaseDelay: 940,
    impactDelay: 1800,
    kind: "strike",
    animation: "physicalCrescentHorn",
    attackStat: "power",
    gutsDamage: 8,
  },
  {
    id: "darkOrbit",
    name: "ダークオービット",
    description: "闇の軌道を飛ばし、ダメージとガッツを同時に削る。",
    iconSvg: icon.darkOrbit,
    cost: 30,
    power: 154,
    accuracy: 70,
    critical: 14,
    range: 2,
    duration: 3200,
    cameraReleaseDelay: 1100,
    impactDelay: 2200,
    kind: "shot",
    animation: "darkOrbit",
    attackStat: "intelligence",
    gutsDamage: 14,
  },
  {
    id: "blackMeteor",
    name: "ブラックメテオ",
    description: "黒い隕石を落とす、超遠距離の高威力な大技。",
    iconSvg: icon.blackMeteor,
    cost: 43,
    power: 230,
    accuracy: 60,
    critical: 25,
    range: 3,
    duration: 4200,
    cameraReleaseDelay: 1200,
    impactDelay: 3000,
    kind: "shot",
    animation: "blackMeteor",
    attackStat: "intelligence",
    gutsDamage: 0,
  },
];

const sutekichiTechniques: TechniqueDefinition[] = [
  {
    id: "starTouch",
    name: "スターダストタッチ",
    description: "星屑をまとった肉球で、高い命中からガッツも削る。",
    iconSvg: icon.starTouch,
    cost: 15,
    power: 68,
    accuracy: 90,
    critical: 8,
    range: 0,
    duration: 2300,
    cameraReleaseDelay: 850,
    impactDelay: 1350,
    kind: "strike",
    animation: "sutekichiStarTouch",
    attackStat: "power",
    gutsDamage: 8,
  },
  {
    id: "haloSkip",
    name: "ハロースキップ",
    description: "光輪とともに跳び込み、威力と命中を両立する。",
    iconSvg: icon.haloSkip,
    cost: 22,
    power: 108,
    accuracy: 80,
    critical: 14,
    range: 1,
    duration: 2900,
    cameraReleaseDelay: 940,
    impactDelay: 1800,
    kind: "strike",
    animation: "sutekichiHaloSkip",
    attackStat: "power",
    gutsDamage: 12,
  },
  {
    id: "stellaSearch",
    name: "ステラサーチ",
    description: "星を探知して狙い撃ちし、ガッツを大きく削る。",
    iconSvg: icon.stellaSearch,
    cost: 29,
    power: 142,
    accuracy: 74,
    critical: 10,
    range: 2,
    duration: 3200,
    cameraReleaseDelay: 1100,
    impactDelay: 2200,
    kind: "shot",
    animation: "sutekichiStellaSearch",
    attackStat: "intelligence",
    gutsDamage: 20,
  },
  {
    id: "discoveryComet",
    name: "ディスカバリー・コメット",
    description: "発見した彗星を呼ぶ、高威力・低命中の大技。",
    iconSvg: icon.discoveryComet,
    cost: 46,
    power: 248,
    accuracy: 56,
    critical: 22,
    range: 3,
    duration: 4200,
    cameraReleaseDelay: 1200,
    impactDelay: 3000,
    kind: "shot",
    animation: "sutekichiDiscoveryComet",
    attackStat: "intelligence",
    gutsDamage: 10,
  },
  {
    id: "nap",
    name: "おひるね",
    description: "成功すればライフを全回復する、気ままな休息技。",
    iconSvg: icon.nap,
    cost: 55,
    power: 0,
    accuracy: 65,
    critical: 0,
    range: 3,
    duration: 4500,
    cameraReleaseDelay: 1100,
    impactDelay: 3000,
    kind: "support",
    animation: "sutekichiNap",
    attackStat: "intelligence",
    gutsDamage: 0,
    healFull: true,
    successChance: 65,
  },
];

const salarymanEtokichiTechniques: TechniqueDefinition[] = [
  {
    id: "businessCardStrike",
    name: "名刺ストライク",
    description: "名刺を鋭く打ち込み、確実にガッツも削る基本技。",
    iconSvg: icon.businessCard,
    cost: 15,
    power: 76,
    accuracy: 91,
    critical: 9,
    range: 0,
    duration: 2300,
    cameraReleaseDelay: 850,
    impactDelay: 1370,
    kind: "strike",
    animation: "businessCardStrike",
    attackStat: "power",
    gutsDamage: 8,
  },
  {
    id: "angelWink",
    name: "エンジェルウィンク",
    description: "魅了を狙いつつガッツを大きく削る、必中級の視線。",
    iconSvg: icon.angelWink,
    cost: 31,
    power: 54,
    accuracy: 86,
    critical: 6,
    range: 2,
    duration: 3200,
    cameraReleaseDelay: 420,
    impactDelay: 2150,
    kind: "shot",
    animation: "angelWink",
    attackStat: "intelligence",
    gutsDamage: 28,
    charmChance: CHARM_EFFECT.triggerChance,
  },
  {
    id: "approvalMeteor",
    name: "稟議書メテオ",
    description: "承認済みの隕石を落とす、超遠距離の高威力技。",
    iconSvg: icon.approvalMeteor,
    cost: 45,
    power: 238,
    accuracy: 58,
    critical: 22,
    range: 3,
    duration: 4200,
    cameraReleaseDelay: 1220,
    impactDelay: 3050,
    kind: "shot",
    animation: "approvalMeteor",
    attackStat: "intelligence",
    gutsDamage: 18,
  },
  {
    id: "closingTimeDash",
    name: "定時ダッシュ",
    description: "一瞬で間合いを詰めて攻撃する、帰宅速度の突進技。",
    iconSvg: icon.closingTime,
    cost: 24,
    power: 126,
    accuracy: 79,
    critical: 15,
    range: 3,
    duration: 550,
    cameraReleaseDelay: 100,
    impactDelay: 400,
    kind: "strike",
    animation: "closingTimeDash",
    attackStat: "power",
    gutsDamage: 14,
    closesDistance: true,
  },
];

const tatsuoTechniques: TechniqueDefinition[] = [
  {
    id: "tatsuoSlap",
    name: "タツヲビンタ",
    description: "素早い平手打ちで、ライフとガッツを手堅く削る。",
    iconSvg: icon.tatsuoSlap,
    cost: 14,
    power: 82,
    accuracy: 92,
    critical: 8,
    range: 0,
    duration: 1050,
    cameraReleaseDelay: 320,
    impactDelay: 430,
    kind: "strike",
    animation: "tatsuoSlap",
    attackStat: "power",
    gutsDamage: 14,
  },
  {
    id: "tatsuoRestraint",
    name: "取り押さえ",
    description: "間合いを詰めて押さえ込み、長時間行動を封じる。",
    iconSvg: icon.tatsuoRestraint,
    cost: 42,
    power: 105,
    accuracy: 63,
    critical: 5,
    range: 1,
    duration: 1900,
    cameraReleaseDelay: 580,
    impactDelay: 940,
    kind: "strike",
    animation: "tatsuoRestraint",
    attackStat: "power",
    gutsDamage: 18,
    restraintDuration: 8000,
    closesDistance: true,
  },
  {
    id: "tatsuoRoar",
    name: "腹の底から咆哮",
    description: "大声で吹き飛ばし、ガッツを一気に奪う咆哮。",
    iconSvg: icon.tatsuoRoar,
    cost: 30,
    power: 35,
    accuracy: 88,
    critical: 4,
    range: 2,
    duration: 2600,
    cameraReleaseDelay: 760,
    impactDelay: 1450,
    kind: "shot",
    animation: "tatsuoRoar",
    attackStat: "intelligence",
    gutsDamage: 46,
    knockback: 42,
  },
  {
    id: "tatsuoPress",
    name: "タツヲプレス",
    description: "遠間から急接近して押し潰す、破格の高威力技。",
    iconSvg: icon.tatsuoPress,
    cost: 50,
    power: 415,
    accuracy: 59,
    critical: 18,
    range: 3,
    duration: 3400,
    cameraReleaseDelay: 900,
    impactDelay: 2400,
    kind: "special",
    animation: "tatsuoPress",
    attackStat: "power",
    gutsDamage: 18,
    knockback: 28,
    closesDistance: true,
  },
];

const asterTechniques: TechniqueDefinition[] = [
  {
    id: "asterTailSweep",
    name: "蛇尾薙ぎ",
    description: "長い尾で薙ぎ払い、相手を近距離から押し戻す。",
    iconSvg: icon.tailSweep,
    cost: 12,
    power: 120,
    accuracy: 70,
    critical: 10,
    range: 1,
    duration: 1800,
    cameraReleaseDelay: 760,
    impactDelay: 1040,
    kind: "strike",
    animation: "asterTailSweep",
    attackStat: "power",
    gutsDamage: 10,
    knockback: 32,
  },
  {
    id: "asterMigration",
    name: "マイグレーション",
    description: "命中は低いが、ライフとガッツを丸ごと吸収する。",
    iconSvg: icon.migration,
    cost: 34,
    power: 105,
    accuracy: 35,
    critical: 4,
    range: 1,
    duration: 3600,
    cameraReleaseDelay: 1180,
    impactDelay: 2380,
    kind: "shot",
    animation: "asterMigration",
    attackStat: "intelligence",
    gutsDamage: 24,
    lifeDrainRatio: 1,
    gutsDrainRatio: 1,
  },
  {
    id: "asterEvilEye",
    name: "魔眼",
    description: "視線でダメージを与え、石化による行動停止を狙う。",
    iconSvg: icon.evilEye,
    cost: 38,
    power: 70,
    accuracy: 60,
    critical: 6,
    range: 2,
    duration: 3900,
    cameraReleaseDelay: 1250,
    impactDelay: 1580,
    kind: "shot",
    animation: "asterEvilEye",
    attackStat: "intelligence",
    gutsDamage: 18,
    petrifyChance: PETRIFICATION_EFFECT.triggerChance,
    petrifyDuration: PETRIFICATION_EFFECT.duration,
  },
  {
    id: "asterDeathEnergy",
    name: "デスエナジー",
    description: "死の力を放ち、遠距離から高威力で吹き飛ばす。",
    iconSvg: icon.deathEnergy,
    cost: 29,
    power: 155,
    accuracy: 65,
    critical: 18,
    range: 3,
    duration: 3200,
    cameraReleaseDelay: 800,
    impactDelay: 1900,
    kind: "shot",
    animation: "asterDeathEnergy",
    attackStat: "intelligence",
    gutsDamage: 10,
    knockback: 20,
  },
];

export function createCharacterProfiles(resolveAsset: AssetResolver): Record<CharacterId, CharacterProfile> {
  const asset = resolveAsset;
  return {
    etokichi: {
      id: "etokichi",
      baseFacing: "right",
      name: "エトキチ",
      subtitle: "GALAXY TRAIL",
      description: "星の力を信じて進む、好奇心旺盛な冒険者。ちからとかしこさを使い分け、逆境ほど真価を発揮する。",
      abilitiesLabel: "底力・根性・余裕・明鏡止水・覚醒",
      images: {
        idle: asset("assets/etokichi/idle.webp"),
        battleIdle: asset("assets/etokichi/walk-right-2.webp"),
        galaxyCharge: asset("assets/etokichi/galaxy-charge.webp"),
        cast: asset("assets/etokichi/cast.webp"),
        galaxyRecoil: asset("assets/etokichi/galaxy-recoil.webp"),
        galaxyRayCast: asset("assets/etokichi/galaxy-ray-cast.webp"),
        punchCast: asset("assets/etokichi/punch-cast.webp"),
        starRingCast: asset("assets/etokichi/star-ring-cast.webp"),
        pentagramNovaWindup: asset("assets/etokichi/pentagram-nova-windup.webp"),
        pentagramNovaRush: asset("assets/etokichi/pentagram-nova-rush.webp"),
        pentagramNovaDive: asset("assets/etokichi/pentagram-nova-dive.webp"),
        etoileDriveCast: asset("assets/etokichi/etoile-drive-cast.webp"),
        throwKissCast: asset("assets/etokichi/throw-kiss-cast.webp"),
        statusSerenity: asset("assets/etokichi/status-serenity.webp"),
        victoryClimax: asset("assets/etokichi/victory-climax.webp"),
        defeat: asset("assets/etokichi/defeat.webp"),
        walk: [1, 2, 3].map((frame) => asset(`assets/etokichi/walk-right-${frame}.webp`)),
      },
      introPoseKeys: ["battleIdle", "punchCast", "battleIdle", "starRingCast"],
      versusPoseKey: "battleIdle",
      stats: { life: 500, power: 410, defense: 420, accuracy: 480, evasion: 430, intelligence: 560, gutsRegen: 2.7 },
      abilities: ["power", "grit", "ease", "serenity", "awakening"],
      techniques: etokichiTechniques,
    },
    kuroboshi: {
      id: "kuroboshi",
      baseFacing: "left",
      name: "クロボシ",
      subtitle: "VOID METEOR",
      description: "負けず嫌いで一直線な黒星のライバル。高い耐久力で攻撃を受け止め、嫉妬を力に変えて押し返す。",
      abilitiesLabel: "本気・余裕・嫉妬",
      images: {
        idle: asset("assets/enemies/kuroboshi/idle.webp"),
        battleIdle: asset("assets/enemies/kuroboshi/idle.webp"),
        darkOrbitCast: asset("assets/enemies/kuroboshi/dark-orbit-cast.webp"),
        blackMeteorCast: asset("assets/enemies/kuroboshi/black-meteor-cast.webp"),
        meteorClawCast: asset("assets/enemies/kuroboshi/meteor-claw-cast.webp"),
        crescentHornCast: asset("assets/enemies/kuroboshi/crescent-horn-cast.webp"),
        statusEase: asset("assets/enemies/kuroboshi/status-ease.webp"),
        statusInspiration: asset("assets/enemies/kuroboshi/status-ease.webp"),
        victoryClimax: asset("assets/enemies/kuroboshi/victory-climax.webp"),
        walk: [1, 2, 3].map((frame) => asset(`assets/enemies/kuroboshi/walk-${frame}.webp`)),
      },
      introPoseKeys: ["idle", "meteorClawCast", "idle", "crescentHornCast"],
      versusPoseKey: "crescentHornCast",
      stats: { life: 625, power: 520, defense: 500, accuracy: 420, evasion: 350, intelligence: 420, gutsRegen: 2.5 },
      abilities: ["real", "ease", "jealousy"],
      techniques: kuroboshiTechniques,
    },
    sutekichi: {
      id: "sutekichi",
      baseFacing: "left",
      name: "ステキチ",
      subtitle: "STELLAR GUIDE",
      description:
        "のんびり屋でお寝坊な、星の兆しを読むゆるふわ案内役。すばやいガッツ回復と高い回避で翻弄し、ひらめきから好機をつかむ。",
      abilitiesLabel: "ひらめき・余裕",
      images: {
        idle: asset("assets/enemies/sutekichi/idle.webp"),
        battleIdle: asset("assets/enemies/sutekichi/idle.webp"),
        stellaSearchCast: asset("assets/enemies/sutekichi/stella-search-cast.webp"),
        discoveryCometCast: asset("assets/enemies/sutekichi/discovery-comet-cast.webp"),
        starTouchCast: asset("assets/enemies/sutekichi/star-touch-cast.webp"),
        haloSkipCast: asset("assets/enemies/sutekichi/halo-skip-cast.webp"),
        napCast: asset("assets/enemies/sutekichi/nap-cast.webp"),
        statusEase: asset("assets/enemies/sutekichi/status-inspiration.webp"),
        statusInspiration: asset("assets/enemies/sutekichi/status-inspiration.webp"),
        statusGenki: asset("assets/enemies/sutekichi/status-genki.webp"),
        victoryClimax: asset("assets/enemies/sutekichi/victory-climax.webp"),
        walk: [1, 2, 3].map((frame) => asset(`assets/enemies/sutekichi/walk-${frame}.webp`)),
      },
      introPoseKeys: ["idle", "starTouchCast", "idle", "haloSkipCast"],
      versusPoseKey: "haloSkipCast",
      stats: { life: 430, power: 330, defense: 300, accuracy: 620, evasion: 780, intelligence: 620, gutsRegen: 5.4 },
      abilities: ["inspiration", "ease"],
      techniques: sutekichiTechniques,
    },
    salarymanEtokichi: {
      id: "salarymanEtokichi",
      baseFacing: "left",
      imageFacings: {
        businessCardStrikeCast: "right",
        closingTimeDashCast: "right",
      },
      visualScale: 1.2,
      name: "サラリーマンエトキチ",
      subtitle: "STELLAR BUSINESS",
      description: "銀河の職場を駆ける仕事人。正確な技と知恵でペースを握り、定時への執念で一気に間合いを詰める。",
      abilitiesLabel: "ひらめき・余裕・ゾーン",
      images: {
        idle: asset("assets/characters/salaryman-etokichi/idle.webp"),
        battleIdle: asset("assets/characters/salaryman-etokichi/idle.webp"),
        businessCardStrikeCast: asset("assets/characters/salaryman-etokichi/business-card-strike-cast.webp"),
        closingTimeDashCast: asset("assets/characters/salaryman-etokichi/closing-time-dash-cast.webp"),
        angelWinkCast: asset("assets/characters/salaryman-etokichi/angel-wink-cast.webp"),
        approvalMeteorCast: asset("assets/characters/salaryman-etokichi/approval-meteor-cast.webp"),
        victoryClimax: asset("assets/characters/salaryman-etokichi/victory-climax.webp"),
        defeat: asset("assets/characters/salaryman-etokichi/defeat.webp"),
        walk: [1, 2, 3].map((frame) => asset(`assets/characters/salaryman-etokichi/walk-${frame}.webp`)),
      },
      introPoseKeys: ["idle", "businessCardStrikeCast", "idle", "angelWinkCast"],
      versusPoseKey: "businessCardStrikeCast",
      stats: { life: 540, power: 430, defense: 470, accuracy: 590, evasion: 440, intelligence: 650, gutsRegen: 3.1 },
      abilities: ["inspiration", "ease", "zone"],
      techniques: salarymanEtokichiTechniques,
    },
    tatsuo: {
      id: "tatsuo",
      baseFacing: "left",
      imageFacings: {
        restraintRush: "right",
      },
      visualScale: 1.08,
      name: "タツヲ",
      subtitle: "SOFT PURSUER",
      description: "大きな体と長い腕で仲間を守る重量級。攻撃を耐えて追いすがり、逃げ場ごと相手を押さえ込む。",
      abilitiesLabel: "本気・追跡・快感",
      images: {
        idle: asset("assets/characters/tatsuo/idle.webp"),
        battleIdle: asset("assets/characters/tatsuo/idle.webp"),
        slapCast: asset("assets/characters/tatsuo/slap-cast.webp"),
        restraintCast: asset("assets/characters/tatsuo/restraint-cast.webp"),
        restraintRush: asset("assets/characters/tatsuo/restraint-rush.webp"),
        restraintPin: asset("assets/characters/tatsuo/restraint-pin.webp"),
        roarCast: asset("assets/characters/tatsuo/roar-cast.webp"),
        pressCast: asset("assets/characters/tatsuo/press-cast.webp"),
        statusPleasure: asset("assets/characters/tatsuo/status-pleasure.webp"),
        victoryClimax: asset("assets/characters/tatsuo/victory-climax.webp"),
        defeat: asset("assets/characters/tatsuo/defeat.webp"),
        walk: [
          asset("assets/characters/tatsuo/walk-1.webp"),
          asset("assets/characters/tatsuo/idle.webp"),
          asset("assets/characters/tatsuo/walk-3.webp"),
        ],
      },
      introPoseKeys: ["idle", "slapCast", "idle", "roarCast"],
      versusPoseKey: "restraintCast",
      stats: { life: 820, power: 600, defense: 540, accuracy: 390, evasion: 250, intelligence: 260, gutsRegen: 2.3 },
      abilities: ["real", "pursuit", "pleasure"],
      techniques: tatsuoTechniques,
    },
    aster: {
      id: "aster",
      baseFacing: "right",
      visualScale: 1.05,
      name: "アステール",
      subtitle: "ORDERED ORACLE",
      description: "魔眼と死の気配をまとう神秘的な策士。高いかしこさと命中で相手を封じ、生命力まで奪い取る。",
      abilitiesLabel: "余裕・本気",
      images: {
        idle: asset("assets/characters/aster/idle.webp"),
        battleIdle: asset("assets/characters/aster/idle.webp"),
        deathEnergyCast: asset("assets/characters/aster/death-energy-cast.webp"),
        evilEyeCast: asset("assets/characters/aster/evil-eye-cast.webp"),
        migrationCast: asset("assets/characters/aster/migration-cast.webp"),
        tailSweepCast: asset("assets/characters/aster/tail-sweep-cast.webp"),
        tailSweepWindup: asset("assets/characters/aster/tail-sweep-windup.webp"),
        tailSweepStrike: asset("assets/characters/aster/tail-sweep-strike.webp"),
        victoryClimax: asset("assets/characters/aster/victory-climax.webp"),
        defeat: asset("assets/characters/aster/defeat.webp"),
        walk: [
          asset("assets/characters/aster/walk-1.webp"),
          asset("assets/characters/aster/idle.webp"),
          asset("assets/characters/aster/walk-3.webp"),
        ],
      },
      introPoseKeys: ["idle", "evilEyeCast", "idle", "deathEnergyCast"],
      versusPoseKey: "evilEyeCast",
      stats: { life: 410, power: 170, defense: 270, accuracy: 820, evasion: 560, intelligence: 860, gutsRegen: 2.4 },
      abilities: ["ease", "real"],
      techniques: asterTechniques,
    },
  };
}
